/jaco_controller:
  ros__parameters:
    cartesian_movement_enabled: True
    normalise_cartesian_speed: False
    relative_cartesian_movement_enabled: False
    max_linear_velocity:
      - 0.05
      - 0.04
      - 0.03
    max_angular_velocity: 5.0
    max_finger_velocity: 2000.0
    discretise_rotation: True
    quantisation_degrees: 30.0
    pid_enabled: True
    kp_linear: 0.8
    ki_linear: 0.1
    kd_linear: 0.00
    kp_angular: 2.0
    ki_angular: 2.0
    kd_angular: 5.00
    camera_rotation_compensation: False
    rotation_assistance: 2.0
